version: '3'

services:
  db:
    image: postgres
    networks:
      - esnet
  web:
    build: .
    command: python3 loremipsum/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HOST=http://localhost:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - esnet

networks:
  esnet:
