# Generated by Django 2.0 on 2018-02-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
