# Generated by Django 2.0 on 2018-02-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
