# Generated by Django 2.0 on 2018-02-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20180224_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.ImageField(default='.jpg', upload_to='media/'),
        ),
    ]
